//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLogin
    {
        public long AdminLoginId { get; set; }
        public string EmailId { get; set; }
        public string AdminPwd { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
