//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryType
    {
        public long CategoryTypeId { get; set; }
        public string CategoryTypeName { get; set; }
        public string SEOCategoryTypeName { get; set; }
        public string CategoryTypeBannerImage { get; set; }
        public string MetaCTTitle { get; set; }
        public string MetaCTKeywords { get; set; }
        public string MetaCTDescriptions { get; set; }
        public string CategoryTypeContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
