//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryImagePath { get; set; }
        public Nullable<long> CategoryTypeId { get; set; }
        public string CategoryTypeName { get; set; }
        public string SEOCategoryName { get; set; }
        public string SEOCategoryTypeName { get; set; }
        public string MetaCatTitle { get; set; }
        public string MetaCatKeywords { get; set; }
        public string MetaCatDescription { get; set; }
        public Nullable<long> Review { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CategoryDescriptionBottom { get; set; }
        public string alias { get; set; }
    }
}
