//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEnquiry
    {
        public long ContactEnquiryId { get; set; }
        public string Name { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string EnquiryMessage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
