//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallpaperHomePageContent
    {
        public long WHPContentId { get; set; }
        public string TrendingThisWeek { get; set; }
        public string TrendingThisWeekContent { get; set; }
        public string FeaturedCategory { get; set; }
        public string FeaturedCategoryContent { get; set; }
        public string TrendingWallpaperAlbums { get; set; }
        public string TrendingWallpaperAlbumsContent { get; set; }
        public string MostViewWallpaperAlbums { get; set; }
        public string MostViewWallpaperAlbumsContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
