//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallpaper
    {
        public long WallpaperId { get; set; }
        public Nullable<long> MainCategoryId { get; set; }
        public string MainCategoryName { get; set; }
        public Nullable<long> CatId { get; set; }
        public string CatName { get; set; }
        public string WallpaperName { get; set; }
        public string SEOMainCategoryName { get; set; }
        public string SEOCatName { get; set; }
        public string SEOWallpaperName { get; set; }
        public string WallpaperImagePath { get; set; }
        public string WallpaperDetail { get; set; }
        public string MetaWallTitle { get; set; }
        public string MetaWallKeywords { get; set; }
        public string MetaWallDescriptions { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
