//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnticingGalary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnticingWallpaperDbEntities : DbContext
    {
        public EnticingWallpaperDbEntities()
            : base("name=EnticingWallpaperDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryType> CategoryTypes { get; set; }
        public virtual DbSet<ContactEnquiry> ContactEnquiries { get; set; }
        public virtual DbSet<WallFaq> WallFaqs { get; set; }
        public virtual DbSet<Wallpaper> Wallpapers { get; set; }
        public virtual DbSet<WallpaperHomePageContent> WallpaperHomePageContents { get; set; }
    }
}
